export const THEME = [
  "light",
  "dark",
  "cupcake",
  "bumblebee",
  "emerald",
  "corporate",
  "synthwave",
  "retro",
  "cyberpunk",
  "valentine",
  "halloween",
  "garden",
  "forest",
  "aqua",
  "lofi",
  "pastel",
  "fantasy",
  "wireframe",
  "black",
  "luxury",
  "dracula",
  "cmyk",
  "autumn",
  "business",
  "acid",
  "lemonade",
  "night",
  "coffee",
  "winter",
];

export const photoStyle = {
  light: "mask mask-squircle",
  dark: "mask mask-squircle",
  cupcake: "rounded-full",
  bumblebee: "mask mask-squircle",
  emerald: "mask mask-squircle",
  corporate: "mask mask-square",
  synthwave: "mask mask-squircle",
  retro: "mask mask-squircle",
  cyberpunk: "mask mask-square",
  valentine: "rounded-full",
  halloween: "mask mask-squircle",
  garden: "mask mask-squircle",
  forest: "rounded-full",
  aqua: "mask mask-squircle",
  lofi: "mask mask-square",
  pastel: "rounded-full",
  fantasy: "mask mask-squircle",
  wireframe: "mask mask-squircle",
  black: "mask mask-square",
  luxury: "mask mask-squircle",
  dracula: "mask mask-squircle",
  cmyk: "mask mask-squircle",
  autumn: "mask mask-squircle",
  business: "mask mask-square",
  acid: "mask mask-squircle",
  lemonade: "mask mask-squircle",
  night: "mask mask-squircle",
  coffee: "mask mask-squircle",
  winter: "mask mask-squircle",
};
